--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Debian 16.8-1.pgdg120+1)
-- Dumped by pg_dump version 17.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: pg_database_owner
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO pg_database_owner;

--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: pg_database_owner
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.account (
    id bigint NOT NULL,
    created_dt timestamp(6) without time zone NOT NULL,
    last_modified_dt timestamp(6) without time zone,
    location character varying(255) NOT NULL,
    password character varying(255),
    username character varying(255),
    fk_owner_id bigint
);


ALTER TABLE public.account OWNER TO audiobook_user;

--
-- Name: account_id_seq; Type: SEQUENCE; Schema: public; Owner: audiobook_user
--

ALTER TABLE public.account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audiobook; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.audiobook (
    id bigint NOT NULL,
    audiobook_title character varying(255) NOT NULL,
    created_dt timestamp(6) without time zone NOT NULL,
    description character varying(512),
    duration character varying(255),
    last_modified_dt timestamp(6) without time zone,
    series_installment character varying(255),
    fk_genre_id bigint,
    fk_owner_id bigint,
    fk_series_id bigint
);


ALTER TABLE public.audiobook OWNER TO audiobook_user;

--
-- Name: audiobook_author; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.audiobook_author (
    audiobook_id bigint NOT NULL,
    author_id bigint NOT NULL
);


ALTER TABLE public.audiobook_author OWNER TO audiobook_user;

--
-- Name: audiobook_id_seq; Type: SEQUENCE; Schema: public; Owner: audiobook_user
--

ALTER TABLE public.audiobook ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audiobook_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audiobook_narrator; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.audiobook_narrator (
    audiobook_id bigint NOT NULL,
    narrator_id bigint NOT NULL
);


ALTER TABLE public.audiobook_narrator OWNER TO audiobook_user;

--
-- Name: author; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.author (
    id bigint NOT NULL,
    created_dt timestamp(6) without time zone NOT NULL,
    first_name character varying(255) NOT NULL,
    last_modified_dt timestamp(6) without time zone,
    last_name character varying(255) NOT NULL
);


ALTER TABLE public.author OWNER TO audiobook_user;

--
-- Name: author_id_seq; Type: SEQUENCE; Schema: public; Owner: audiobook_user
--

ALTER TABLE public.author ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.author_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: genre; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.genre (
    id bigint NOT NULL,
    genre character varying(255) NOT NULL
);


ALTER TABLE public.genre OWNER TO audiobook_user;

--
-- Name: genre_id_seq; Type: SEQUENCE; Schema: public; Owner: audiobook_user
--

ALTER TABLE public.genre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.genre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: narrator; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.narrator (
    id bigint NOT NULL,
    created_dt timestamp(6) without time zone NOT NULL,
    first_name character varying(255) NOT NULL,
    last_modified_dt timestamp(6) without time zone,
    last_name character varying(255) NOT NULL
);


ALTER TABLE public.narrator OWNER TO audiobook_user;

--
-- Name: narrator_id_seq; Type: SEQUENCE; Schema: public; Owner: audiobook_user
--

ALTER TABLE public.narrator ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.narrator_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: owner; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.owner (
    id bigint NOT NULL,
    created_dt timestamp(6) without time zone NOT NULL,
    first_name character varying(255) NOT NULL,
    last_modified_dt timestamp(6) without time zone,
    last_name character varying(255) NOT NULL,
    source character varying(255)
);


ALTER TABLE public.owner OWNER TO audiobook_user;

--
-- Name: owner_id_seq; Type: SEQUENCE; Schema: public; Owner: audiobook_user
--

ALTER TABLE public.owner ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.owner_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: series; Type: TABLE; Schema: public; Owner: audiobook_user
--

CREATE TABLE public.series (
    id bigint NOT NULL,
    series_name character varying(255) NOT NULL,
    total_count integer NOT NULL
);


ALTER TABLE public.series OWNER TO audiobook_user;

--
-- Name: series_id_seq; Type: SEQUENCE; Schema: public; Owner: audiobook_user
--

ALTER TABLE public.series ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.series_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: account; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.account (id, created_dt, last_modified_dt, location, password, username, fk_owner_id) FROM stdin;
\.


--
-- Data for Name: audiobook; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.audiobook (id, audiobook_title, created_dt, description, duration, last_modified_dt, series_installment, fk_genre_id, fk_owner_id, fk_series_id) FROM stdin;
1	Troy	2025-05-15 08:33:48.681	Greek Mythology	12:30:00	2025-05-15 17:58:12.014	3	1	1	1
2	Mythos	2025-05-15 18:00:22.052	Greek Mythology	12:30:00	\N	1	1	1	1
3	Heroes	2025-05-15 18:00:51.848	Greek Mythology	12:30:00	\N	2	1	1	1
4	Odyssey	2025-05-15 18:01:07.327	Greek Mythology	12:30:00	\N	4	1	1	1
\.


--
-- Data for Name: audiobook_author; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.audiobook_author (audiobook_id, author_id) FROM stdin;
2	3
3	3
4	3
1	3
\.


--
-- Data for Name: audiobook_narrator; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.audiobook_narrator (audiobook_id, narrator_id) FROM stdin;
2	1
3	1
4	1
1	1
\.


--
-- Data for Name: author; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.author (id, created_dt, first_name, last_modified_dt, last_name) FROM stdin;
2	2025-05-15 17:06:26.363	Alexia	\N	Coombs
3	2025-05-15 17:07:11.462	Stephen	\N	Fry
4	2025-05-15 17:07:27.396	Jack	\N	Carr
5	2025-05-15 17:07:52.479	Charles	\N	Dickens
\.


--
-- Data for Name: genre; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.genre (id, genre) FROM stdin;
1	Fiction
\.


--
-- Data for Name: narrator; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.narrator (id, created_dt, first_name, last_modified_dt, last_name) FROM stdin;
1	2025-05-15 17:32:43.568	Stephen	\N	Fry
2	2025-05-15 17:33:28.394	Brene	\N	Brown
3	2025-05-15 17:40:44.245	Brene	\N	Brown
\.


--
-- Data for Name: owner; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.owner (id, created_dt, first_name, last_modified_dt, last_name, source) FROM stdin;
1	2025-05-15 17:48:23	Laura	\N	Coombs	\N
\.


--
-- Data for Name: series; Type: TABLE DATA; Schema: public; Owner: audiobook_user
--

COPY public.series (id, series_name, total_count) FROM stdin;
1	Mythos	4
\.


--
-- Name: account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: audiobook_user
--

SELECT pg_catalog.setval('public.account_id_seq', 1, false);


--
-- Name: audiobook_id_seq; Type: SEQUENCE SET; Schema: public; Owner: audiobook_user
--

SELECT pg_catalog.setval('public.audiobook_id_seq', 5, true);


--
-- Name: author_id_seq; Type: SEQUENCE SET; Schema: public; Owner: audiobook_user
--

SELECT pg_catalog.setval('public.author_id_seq', 5, true);


--
-- Name: genre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: audiobook_user
--

SELECT pg_catalog.setval('public.genre_id_seq', 1, true);


--
-- Name: narrator_id_seq; Type: SEQUENCE SET; Schema: public; Owner: audiobook_user
--

SELECT pg_catalog.setval('public.narrator_id_seq', 3, true);


--
-- Name: owner_id_seq; Type: SEQUENCE SET; Schema: public; Owner: audiobook_user
--

SELECT pg_catalog.setval('public.owner_id_seq', 1, true);


--
-- Name: series_id_seq; Type: SEQUENCE SET; Schema: public; Owner: audiobook_user
--

SELECT pg_catalog.setval('public.series_id_seq', 1, true);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (id);


--
-- Name: audiobook_author audiobook_author_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook_author
    ADD CONSTRAINT audiobook_author_pkey PRIMARY KEY (audiobook_id, author_id);


--
-- Name: audiobook_narrator audiobook_narrator_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook_narrator
    ADD CONSTRAINT audiobook_narrator_pkey PRIMARY KEY (audiobook_id, narrator_id);


--
-- Name: audiobook audiobook_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook
    ADD CONSTRAINT audiobook_pkey PRIMARY KEY (id);


--
-- Name: author author_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.author
    ADD CONSTRAINT author_pkey PRIMARY KEY (id);


--
-- Name: genre genre_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.genre
    ADD CONSTRAINT genre_pkey PRIMARY KEY (id);


--
-- Name: narrator narrator_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.narrator
    ADD CONSTRAINT narrator_pkey PRIMARY KEY (id);


--
-- Name: owner owner_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.owner
    ADD CONSTRAINT owner_pkey PRIMARY KEY (id);


--
-- Name: series series_pkey; Type: CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.series
    ADD CONSTRAINT series_pkey PRIMARY KEY (id);


--
-- Name: audiobook_author fk8ixsw55wwc2hcqnevrkcu0f25; Type: FK CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook_author
    ADD CONSTRAINT fk8ixsw55wwc2hcqnevrkcu0f25 FOREIGN KEY (author_id) REFERENCES public.author(id);


--
-- Name: audiobook fkchjc4deqbs7cvkfetj3jurdc5; Type: FK CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook
    ADD CONSTRAINT fkchjc4deqbs7cvkfetj3jurdc5 FOREIGN KEY (fk_owner_id) REFERENCES public.owner(id);


--
-- Name: audiobook_narrator fkdkb3cislnnml8kodft8ar3af5; Type: FK CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook_narrator
    ADD CONSTRAINT fkdkb3cislnnml8kodft8ar3af5 FOREIGN KEY (audiobook_id) REFERENCES public.audiobook(id);


--
-- Name: audiobook_narrator fkgcrfsqrqr28abt3ck3eenu0nx; Type: FK CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook_narrator
    ADD CONSTRAINT fkgcrfsqrqr28abt3ck3eenu0nx FOREIGN KEY (narrator_id) REFERENCES public.narrator(id);


--
-- Name: audiobook fkh5pekkbvtqtlurg6pdel70xbd; Type: FK CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook
    ADD CONSTRAINT fkh5pekkbvtqtlurg6pdel70xbd FOREIGN KEY (fk_genre_id) REFERENCES public.genre(id);


--
-- Name: audiobook fkhf7tktpbausvdvpa41u22uggg; Type: FK CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook
    ADD CONSTRAINT fkhf7tktpbausvdvpa41u22uggg FOREIGN KEY (fk_series_id) REFERENCES public.series(id);


--
-- Name: audiobook_author fki5f3st72tcl6hifb8jix9kwxm; Type: FK CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.audiobook_author
    ADD CONSTRAINT fki5f3st72tcl6hifb8jix9kwxm FOREIGN KEY (audiobook_id) REFERENCES public.audiobook(id);


--
-- Name: account fkq74ae8xlns7rvemhcit88wmp3; Type: FK CONSTRAINT; Schema: public; Owner: audiobook_user
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT fkq74ae8xlns7rvemhcit88wmp3 FOREIGN KEY (fk_owner_id) REFERENCES public.owner(id);


--
-- PostgreSQL database dump complete
--

