services:
  postgres:
    image: postgres:16
    container_name: audiobook_postgres
    environment:
      POSTGRES_DB: audiobook_db
      POSTGRES_USER: audiobook_user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  pgdata:
